language: python
sudo: false
cache: pip

python:
  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"

before_install:
  - pip install -U pip
  - sudo apt-get install gfortran
  - sudo apt install gcc
  - pip install -r requirements.txt

install:
  - pip install coveralls
  - pip install coverage
  - pip install Cython
  #  - pip install -e .
  - python setup.py install

script:
  - coverage run --source pyrism/ -m pytest

after_success:
  - coveralls